In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
pd.set_option('display.max_colwidth', 100) #Sets max coloumn with for displaying dataframes

stops_cols = ["Longitude", "Latitude"]
stops = pd.read_csv('stops.csv',names=stops_cols)
distances_cols = ['stop0','stop1','stop2','stop3','stop4','stop5','stop6','stop7','stop8','stop9','stop10','stop11']
distances = pd.read_csv('distances.csv',names=distances_cols)
distance_matrix = distances.to_numpy()

display(stops,distances)

Longitude  Latitude
0    6.084592  3.647243
1    3.757416  5.566100
2    4.804498  4.596598
3    4.703749  4.920296
4   -8.178210 -0.909409
5   -7.778165 -1.765424
6   -7.054886 -2.096278
7   -8.078685 -0.019262
8    0.319826  1.534481
9    1.489526  2.431312
10   0.123605 -0.630716
11  -2.544777 -0.173198

stop0      stop1      stop2      stop3      stop4      stop5   
0    0.000000   3.016249   1.593711   1.878135  14.972996  14.881969  \
1    3.016249   0.000000   1.426995   1.145691  13.579080  13.668243   
2    1.593711   1.426995   0.000000   0.339015  14.102015  14.099600   
3    1.878135   1.145691   0.339015   0.000000  14.139672  14.159697   
4   14.972996  13.579080  14.102015  14.139672   0.000000   0.944880   
5   14.881969  13.668243  14.099600  14.159697   0.944880   0.000000   
6   14.339942  13.252092  13.617620  13.692984   1.634171   0.795359   
7   14.630164  13.087764  13.685123  13.703644   0.895693   1.771833   
8    6.139730   5.298205   5.430363   5.539180   8.842467   8.744531   
9    4.753223   3.869137   3.959483   4.065252  10.228662  10.173626   
10   7.337186   7.183670   7.016806   7.196627   8.306492   7.982827   
11   9.437255   8.523919   8.761438   8.859165   5.681336   5.470240   

        stop6      stop7     stop8      stop9    stop10    stop11  
0   14.339942  14.630164  6.139730   4.753223  7.337186  9.437255  
1   13.252092  13.087764  5.298205   3.869137  7.183670  8.523919  
2   13.617620  13.685123  5.430363   3.959483  7.016806  8.761438  
3   13.692984  13.703644  5.539180   4.065252  7.196627  8.859165  
4    1.634171   0.895693  8.842467  10.228662  8.306492  5.681336  
5    0.795359   1.771833  8.744531  10.173626  7.982827  5.470240  
6    0.000000   2.315634  8.220024   9.669853  7.326569  4.902991  
7    2.315634   0.000000  8.541025   9.877043  8.225050  5.536049  
8    8.220024   8.541025  0.000000   1.473941  2.174070  3.334985  
9    9.669853   9.877043  1.473941   0.000000  3.352873  4.801986  
10   7.326569   8.225050  2.174070   3.352873  0.000000  2.707321  
11   4.902991   5.536049  3.334985   4.801986  2.707321  0.000000

In [ ]:
def average_distance(distance_matrix):
    total_distance = 0
    num_stops = len(distance_matrix)
    print(num_stops)
    num_pairs = 0

    for i in range(num_stops):
        for j in range(i + 1, num_stops):
            total_distance += distance_matrix[i][j]
            num_pairs += 1

    return total_distance / num_pairs

# Assuming distance_matrix is available for 12 stops
avg_distance = average_distance(distance_matrix)
print("Average distance between each stop:", avg_distance)
print("Average distance for each route group", avg_distance*3)

Generate Random Solution

In [4]:
import random

class Generate():
    def __init__(self):
        self.num_vessels = 3
        self.stops_per_route = 4
        self.routes_np = None
        self.stops = stops
        self.stop_indices = list(range(0, len(stops)))
        

    def make_random_solution(self): # Generate initial solution
        random.shuffle(self.stop_indices)
        # divide the stops into sublists of length stops_per_route
        routes = np.array_split(self.stop_indices, self.num_vessels)
        self.routes_np = np.array(routes)
        return self.routes_np
    
    @property # Getter, no need to access like a method()
    def get_routes(self): # Can be called to obtain the current solution routes
        if self.routes_np is None:
            self.make_random_solution()
        return self.routes_np

generate = Generate() # Instantiate the Generate class


Fitness function

In [5]:
# def calc_route_distance(choosen_route):
#     # print(f"🚢 Ferry Route #{i} : {choosen_route}")
#     total_distance = 0
#     # route_distance_matrix = []
#     for i, stop in enumerate(choosen_route):
#         if i < len(choosen_route) - 1:
#             next_stop = choosen_route[i + 1]
#             # route_distance_matrix.append((distance_matrix[stop][next_stop]))
#             total_distance += distance_matrix[stop][next_stop]
#         # Return back to the origin stop (Circuit)
#     total_distance += distance_matrix[choosen_route][-1][choosen_route][0]
#     # route_distance_matrix.append(([choosen_route][-1][choosen_route][0]))
#     # print(route_distance_matrix)
#     return total_distance



def calc_route_distance(choosen_route):
    total_distance = 0
    route_distance_matrix = []
    for i, stop in enumerate(choosen_route):
        if i < len(choosen_route) - 1:
            next_stop = choosen_route[i + 1]
            route_distance_matrix.append((distance_matrix[stop][next_stop]))
            total_distance += distance_matrix[stop][next_stop]
        # Return back to the origin stop (Circuit)
    total_distance += distance_matrix[choosen_route][-1][choosen_route][0]
    route_distance_matrix.append((distance_matrix[choosen_route][-1][choosen_route][0]))
    # group_std_deviation = np.std(choosen_route )
    # print(choosen_route)
    # print(route_distance_matrix)
    return total_distance,route_distance_matrix



    

def test_fitness(routes):
    total_violations = 0
    tolerance_distance = 5
    mean_distance = []
    route_distance = []
    for route in routes:
         #Returns the Route Distance(rd) for each group of 4, Returns Each Path Distance(epd)
         rd,epd = calc_route_distance(route)
         route_distance.append(rd)
         mean_distance.append(np.mean(epd))
        #  mean_length = np.mean(epd)
 
    std_dev = np.std(mean_distance) # Less then 1.0 means the route lengths are more or less even.
    # threshold = 1.0
    # if std_dev < threshold:
    #   print("The mean distances are roughly even.")
    # else:
    #  print("The mean distances are not even.")
        # route_distance.append(calc_route_distance(route))
        
    fitness_score = np.sum(route_distance) * std_dev
    # return route_distance,mean_distance,std_dev
    return fitness_score,mean_distance,std_dev
    
    
    
    
    
    # def test_fitness(routes):
    # total_violations = 0
    # tolerance_distance = 5
    # route_distance = []
    # for i,route in enumerate(routes):
    #     print("ROUTE" ,routes)
    #     route_distance.append(calc_route_distance(routes[i],i))
    # # print("Route distance :" ,route_distance)
    # # max_distance = max(route_distance)
    # # min_distance = min(route_distance)
    # # print("max" , max_distance)
    # # print("min", min_distance)
    # # return "Total Violations: " ,total_violations
    # # print("Fitness score ", np.sum(route_distance))
    # # print(route_distance)
    # return route_distance

Create 3 Mutation operator's, Shuffle, Swap & Ruin-Recreate

In [6]:
import copy #For deep copy 2d arrays

class InvalidRouteNumberError(Exception):
    pass

class Mutation_Operators():
    def __init__(self):
        pass
    
    def shuffle(self,solution):
        child = copy.deepcopy(solution)
        random_group = np.random.randint(0,len(child))
        np.random.shuffle(child[random_group])
        return child
        
    
    def swap(self,solution): # Pick two random stops and exchange their locations within the three routes+
        child = copy.deepcopy(solution)
        idx1, idx2 = np.random.choice(len(stops), 2, replace=False)
        loc1 = np.argwhere(child == idx1).flatten()
        loc2 = np.argwhere(child == idx2).flatten()
        child[tuple(loc1)], child[tuple(loc2)] = child[tuple(loc2)],child[tuple(loc1)]
        return child

       
        
    def ruin_and_recreate(self,best_solution):
        return generate.make_random_solution()
        

    
try:
   pass
    # mo = Mutation_Operators()
    # hc.shuffle(0)
    # print(routes)
    # hc.swap()
    # hc.ruin_and_recreate()
    # mo.ruin_and_recreate()
    # mo.shuffle(generate.get_routes)
except InvalidRouteNumberError as e:
    print(e)
    

In [265]:
import copy


class HillClimber():
    def __init__(self):
        # Instantiate the class containing the operators
        self.mo = Mutation_Operators() #Instantiate the class containing the operaters
        
        # Generate initial random solution
        self.initial_random_solution = generate.make_random_solution()    
        self.best_solution = copy.deepcopy(self.initial_random_solution)
        self.initial_fitness,self.mean_distance,self.std_dev = test_fitness(self.best_solution)
        self.initial_fitness = np.sum(self.initial_fitness)
        self.best_fitness = copy.deepcopy(self.initial_fitness)
        self.best_overall = []
        self.fit = []
        
        # Define the operator list
        self.operator_list =  [
                                {"label" : "Swap", "operator" : self.mo.swap},
                                {"label" : "Shuffle", "operator" : self.mo.shuffle},
                                {"label" : "Ruin and Create", "operator" : self.mo.ruin_and_recreate},     
                        ]
       
      
        
    def runMutationOperators(self,operatorIterations):
        # fit = []
        
        for operator in self.operator_list: 
            label = operator["label"]
            mutation_operator = operator["operator"] 
            self.fit.append((label,"Initial",self.initial_random_solution,self.mean_distance,self.std_dev,self.initial_fitness,self.best_fitness))
            for _ in range(operatorIterations):
                child_solution = mutation_operator(self.best_solution)
                child_fitness,self.mean_distance,self.std_dev = test_fitness(child_solution)
                child_fitness = np.sum(child_fitness)
                            
                if child_fitness < self.best_fitness:
                    # print("CHILD Won", child_fitness, "VS", best_fitness)
                    self.best_solution = copy.deepcopy(child_solution)
                    self.best_fitness = copy.deepcopy(child_fitness)
                       
                # else:
                #     print("PARENT WON", best_fitness, "VS", child_fitness)
            
                self.fit.append((label,_,child_solution,self.mean_distance,self.std_dev,child_fitness,self.best_fitness))

            # print("Best solution for ",label, "after", operatorIterations, "rounds." , "Best fitness score", best_fitness)
            # print(best_solution)
            # print("-------------")
            # avg_fit = 
            # max_fit =max(child_fitness)
            # min_fit = min(self.best_fitness)
            # print(fit)
            # print("MAX FIT",5)
            self.best_overall.append((label,self.best_fitness,self.best_solution))
        # Reset Solutions & Fitness for next operator to initial random values
            self.best_solution = copy.deepcopy(self.initial_random_solution)
            self.best_fitness = copy.deepcopy(self.initial_fitness)
        
        
        return self.fit,self.best_overall
            
    
    
    def runHillClimber(self,algoIterations,operatorIterations):
        best_world = []
        aggregations = []
        columns=["Mutation", "Round #", "Solution","Mean_Distance" ,"Standard Dev", "Fitness score", "Best Fitness"]
        for _ in range(algoIterations):
            fit,best_overall = self.runMutationOperators(operatorIterations)
            agg = pd.DataFrame(fit,columns=columns).groupby("Mutation")["Fitness score"].agg(["max", "min", "mean"])
            aggregations.append(agg)
            # best_world.append(best_overall)
        self.fit = []
        # print(avg)
        # print(best_world[0][1])
        # maxFit = max(best_world)
        # print("MAX FIT", maxFit)
    
        return fit,best_overall,aggregations
       
    
    

    

What was the best solution and best score for each operator?

In [268]:
pd.set_option('display.max_rows', None)
hc = HillClimber()
operatorIterations = 30
algoIterations = 5
fit,best_overall,agg = hc.runHillClimber(algoIterations,operatorIterations)
# just = pd.DataFrame(agg)
display(agg)
# max = max(fit[3]
# print(max)
# print(fit)
column_headings = ["Mutation", "Round #", "Solution","Mean_Distance" ,"Standard Dev", "Fitness score", "Best Fitness"]
dataframe = pd.DataFrame(fit,columns=column_headings)
# result = dataframe.groupby("Mutation")["Fitness score"].agg(["max", "min", "mean"])
# print(result)
# best_overall_df = pd.DataFrame(best_overall,columns=["Mutation","Best Fitness Score", "Best Solution"])
# title = f"Best Overall for {algoIterations} Algorithm run and {operatorIterations} mutation runs each"
# print(title)
# print("-" * len(title))
# display(best_overall_df)
# # display(best_overall_df.sort_values(by='Best Fitness Score'))
# title = "Detailed Mutation List"
# print(title)
# display(dataframe)

[                        max       min        mean
 Mutation                                         
 Ruin and Create  438.794804  7.972236  124.008060
 Shuffle          198.470768  7.841847   49.713938
 Swap             287.364753  1.566899   50.285021,
                         max       min        mean
 Mutation                                         
 Ruin and Create  462.091554  7.972236  136.928918
 Shuffle          198.470768  7.841847   59.978549
 Swap             287.364753  1.566899   64.585069,
                         max       min        mean
 Mutation                                         
 Ruin and Create  462.091554  7.972236  132.972257
 Shuffle          198.470768  7.841847   64.111864
 Swap             287.364753  1.566899   72.359465,
                         max       min        mean
 Mutation                                         
 Ruin and Create  462.091554  7.972236  133.547826
 Shuffle          198.470768  7.841847   67.184351
 Swap             287.364753

In [ ]:
mo = Mutation_Operators() #Instantiate the class
fit = []
best_solution = generate.make_random_solution()
best_fitness = np.sum(test_fitness(best_solution))
for _ in range(50):
        child_solution = mo.ruin_and_recreate(best_solution)
        child_fitness = np.sum(test_fitness(child_solution))
        if child_fitness < best_fitness:
            best_solution = child_solution
            best_fitness = child_fitness
        fit.append(best_fitness)
print(fit)
 

Plot results over single in

In [ ]:
# grouped_scores = {}
# fit,operator_list = hill_climber(300)
# for dictionary in fit:
#     label = dictionary['label']
#     score = dictionary['fitness_score']
#     iteration = dictionary['iteration']
#     if label in grouped_scores:
#         grouped_scores[label]['scores'].append(score)
#         grouped_scores[label]['iterations'].append(iteration)
#     else:
#         grouped_scores[label] = {'scores': [score], 'iterations': [iteration]}

# for label, data in grouped_scores.items():
#     iterations = data['iterations']
#     scores = data['scores']
#     average_score = np.mean(scores)
#     plt.plot(iterations, [average_score] * len(iterations), label=label)
    
# plt.title('Fitness Scores by Mutator and Iteration')
# plt.xlabel('Iteration')
# plt.ylabel('Fitness Score')
# plt.legend()
# plt.show()





In [199]:
fit,best,operator_list = hill_climber(30)

🚢 Ferry Route  : [11  9  2  5]
[11  9  2  5]
[4.801986346248775, 3.9594828151568975, 14.099599990816492, 5.470240084758848]
🚢 Ferry Route  : [7 6 8 4]
[7 6 8 4]
[2.315633654789475, 8.220024320026443, 8.842467049084032, 0.8956932546304843]
🚢 Ferry Route  : [ 3  0  1 10]
[ 3  0  1 10]
[1.8781350742507348, 3.0162494626162135, 7.183669840854041, 7.196627323673687]
🚢 Ferry Route  : [11  9  2  5]
[11  9  2  5]
[4.801986346248775, 3.9594828151568975, 14.099599990816492, 5.470240084758848]
🚢 Ferry Route  : [ 7  6  8 10]
[ 7  6  8 10]
[2.315633654789475, 8.220024320026443, 2.1740701065266888, 8.225049778146742]
🚢 Ferry Route  : [3 0 1 4]
[3 0 1 4]
[1.8781350742507348, 3.0162494626162135, 13.579079534273053, 14.139672108453924]
🚢 Ferry Route  : [6 9 2 5]
[6 9 2 5]
[9.669852629159196, 3.9594828151568975, 14.099599990816492, 0.7953592716371841]
🚢 Ferry Route  : [ 7 11  8  4]
[ 7 11  8  4]
[5.536048628108121, 3.3349845032193843, 8.842467049084032, 0.8956932546304843]
🚢 Ferry Route  : [ 3  0  1 10]


ValueError: not enough values to unpack (expected 3, got 2)

In [200]:
#  for operator in operator_list: 
#      print(operator["label"])
     


# Group the fitness data by label
grouped_fit = {}
for item in fit:
    label = item["label"]
    if label not in grouped_fit:
        grouped_fit[label] = {"y": []}
    # grouped_fit[label]["x"].append(item["iteration"])
    grouped_fit[label]["y"].append(item["fitness_score"])

# print(grouped_fit)

# Plot a line chart of the grouped fitness data
fig, ax = plt.subplots()
for label, data in grouped_fit.items():
    # ax.plot(data["x"], data["y"], label=label)
    ax.plot(data["y"],label=label)
ax.set_ylabel("Fitness Score")
ax.set_xlabel("Iteration")
ax.set_title("Fitness Scores by Label")
ax.legend()
plt.show()

TypeError: tuple indices must be integers or slices, not str